<?php

/**
 * BaseNote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $content
 * @property string $tag
 * 
 * @method string getTitle()   Returns the current record's "title" value
 * @method string getContent() Returns the current record's "content" value
 * @method string getTag()     Returns the current record's "tag" value
 * @method Note   setTitle()   Sets the current record's "title" value
 * @method Note   setContent() Sets the current record's "content" value
 * @method Note   setTag()     Sets the current record's "tag" value
 * 
 * @package    oibdc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNote extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('note');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('tag', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}
