<?php

/**
 * BaseBMP
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ip
 * @property string $content
 * @property string $email
 * 
 * @method string getIp()      Returns the current record's "ip" value
 * @method string getContent() Returns the current record's "content" value
 * @method string getEmail()   Returns the current record's "email" value
 * @method BMP    setIp()      Sets the current record's "ip" value
 * @method BMP    setContent() Sets the current record's "content" value
 * @method BMP    setEmail()   Sets the current record's "email" value
 * 
 * @package    oibdc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBMP extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('b_m_p');
        $this->hasColumn('ip', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('content', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}