<?php

/**
 * BMPTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BMPTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BMPTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BMP');
    }
}