<?php

/**
 * NoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Note');
    }
    static public function addIndexFor($note, $index)
    {
        $doc = new Zend_Search_Lucene_Document();
        // store note primary key to identify it in the search results
        $doc->addField(Zend_Search_Lucene_Field::Keyword('pk', $note->getId()));
        // index note fields
        $doc->addField(Zend_Search_Lucene_Field::UnStored('title', $note->getTitle(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('content', $note->getContent(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('tag', $note->getTag(), 'utf-8'));
        // add note to the index
        $index->addDocument($doc);
        $index->commit();
    }
    static public function getLuceneIndex()
    {
        ProjectConfiguration::registerZend();
        $index = self::getLuceneIndexFile();
        if (file_exists($index)) {
            return Zend_Search_Lucene::open($index);
        }
        $indexf = Zend_Search_Lucene::create($index);
        $notes = Doctrine_Core::getTable('note')->createQuery('a')->execute();;
        foreach($notes as $note) {
            self::addIndexFor($note, $indexf);
        }
        return $indexf;
    }
    static public function getLuceneIndexFile()
    {
        return sfConfig::get('sf_cache_dir').'/note.'.sfConfig::get('sf_environment').'.index';
    }
}
