<?php

/**
 * Note
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    oibdc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Note extends BaseNote
{
    public function save(Doctrine_Connection $conn = null)
    {
        $conn = $conn ? $conn : $this->getTable()->getConnection();
        $conn->beginTransaction();
        try {
            $ret = parent::save($conn);
            $this->updateLuceneIndex();
            $conn->commit();
            return $ret;
        } catch (Exception $e) {
            $conn->rollBack();
            throw $e;
        }
    }
    public function updateLuceneIndex()
    {
        $index = NoteTable::getLuceneIndex();
        // remove existing entries
        foreach ($index->find('pk:'.$this->getId()) as $hit) {
            $index->delete($hit->id);
        }
        NoteTable::addIndexFor($this,$index);
    }
    public function delete(Doctrine_Connection $conn = null)
    {
        $index = NoteTable::getLuceneIndex();
        foreach ($index->find('pk:'.$this->getId()) as $hit) {
            $index->delete($hit->id);
        }
        return parent::delete($conn);
    }
}
